"""
Django settings for Core project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config, Csv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k9r^odfr7iwph!26sc*3u57l942)al9lz$t20o1#arua)f5g)t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', '10.0.2.2', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "django_filters",
    "drf_spectacular",
    "tomato_grading_api",
    'django.contrib.gis',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "tomato_grading_api.middleware.DebugRequestMiddleware",
    "tomato_grading_api.middleware.AuthenticationDebugMiddleware",
]

ROOT_URLCONF = 'Core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'farmlink',
        'USER': 'farmlink_user',
        'PASSWORD': 'strongpassword',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# ── Cache
CACHES = {
    "default": {
        "BACKEND":  "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "tomato-grading",
    }
}

# ── REST Framework ────────────────────────────────────────────────────────────
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FormParser",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    # "DEFAULT_THROTTLE_RATES": {
    #     "grade": "30/hour",
    #     "price": "60/hour",
    #     "login": "5/hour",
    #     "register": "3/hour",
    #     "2fa": "10/minute",
    #     "verify-email": "5/hour",
    #     "setup-2fa": "3/hour",
    #     "forgot_password": "3/hour",
    #     "password_reset": "3/hour",
    #     "anon": "100/day",
    #     "user": "1000/day",
    # },

    "DEFAULT_THROTTLE_RATES": {
        "grade": "20/minute",
        "price": "30/minute",

        "login": "20/hour",
        "register": "5/hour",

        "2fa": "5/minute",
        "verify-email": "5/hour",
        "setup-2fa": "3/hour",

        "forgot_password": "3/hour",
        "password_reset": "3/hour",

        "anon": "200/day",
        "user": "2000/day"
    },
}

# ── JWT ───────────────────────────────────────────────────────────────────────
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME":  timedelta(minutes=config("JWT_ACCESS_MINUTES", default=60, cast=int)),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=config("JWT_REFRESH_DAYS", default=7, cast=int)),
    "ROTATE_REFRESH_TOKENS":  True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES":      ("Bearer",),
    "UPDATE_LAST_LOGIN":      True,
}

# ── CORS ──────────────────────────────────────────────────────────────────────
CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:3000,http://localhost:8081,http://127.0.0.1:8081,http://127.0.0.1:3000",
    cast=Csv()
)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True  # For development only

# ── Media & Static ────────────────────────────────────────────────────────────
MEDIA_URL   = config("MEDIA_URL",  default="/media/")
MEDIA_ROOT  = BASE_DIR / config("MEDIA_ROOT", default="media")
STATIC_URL  = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MAX_UPLOAD_SIZE   = config("MAX_UPLOAD_SIZE_MB", default=10, cast=int) * 1024 * 1024
ALLOWED_IMAGE_TYPES = ["image/jpeg", "image/png", "image/webp", "image/bmp"]

# ── ML Model Configuration (v2 — both models) ─────────────────────────────────
#
# Place all model files in the directory pointed to by MODEL_DIR.
# Required files:
#   • tomato_grader_rf_pipeline.pkl  — grading model (from grading Colab)
#   • model_metadata.json            — grading model metadata
#   • tomato_pricing_model.pkl       — pricing model (from pricing Colab)
#   • pricing_model_metadata.json    — pricing model metadata
#
ML_MODEL_DIR = Path(config("MODEL_DIR", default=str(BASE_DIR / "models")))

ML_CONFIG = {
    # ── Grading model (unchanged from v1) ────────────────────────────────────
    "model_path":    ML_MODEL_DIR / config("RF_MODEL_FILE",  default="tomato_grader_rf_pipeline.pkl"),
    "metadata_path": ML_MODEL_DIR / config("METADATA_FILE",  default="model_metadata.json"),
    "img_size":      (224, 224),
    "confidence_thresholds": {
        "high":   85.0,
        "medium": 60.0,
    },

    # ── Pricing model (new in v2) ─────────────────────────────────────────────
    "pricing_model_path": ML_MODEL_DIR / config(
        "PRICING_MODEL_FILE", default="tomato_pricing_model.pkl"
    ),
    "pricing_meta_path": ML_MODEL_DIR / config(
        "PRICING_META_FILE", default="pricing_model_metadata.json"
    ),
}

# ── API Documentation ─────────────────────────────────────────────────────────
SPECTACULAR_SETTINGS = {
    "TITLE":       "Tomato Grading & Pricing API",
    "DESCRIPTION": (
        "Unified ML inference pipeline for Zimbabwe tomato market. "
        "POST an image + 4 context inputs → receive a grade AND price estimate "
        "in a single call. Grades: A (Premium), B (Good), C (Fair)."
    ),
    "VERSION":     "2.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "CONTACT": {"name": "Local Roots", "email": "dev@localroots.co.zw"},
    "TAGS": [
        {"name": "pipeline",  "description": "Full grade-and-price inference pipeline"},
        {"name": "history",   "description": "Session history and lookup"},
        {"name": "feedback",  "description": "Model feedback and corrections"},
        {"name": "analytics", "description": "Aggregate statistics"},
        {"name": "auth",      "description": "Authentication"},
        {"name": "health",    "description": "System health"},
    ],
}

# ── LOGGING ─────────────────────────────────────────────────────────────────────
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'api': {
            'format': '[{asctime}] {levelname} [{name}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'api_requests': {
            'class': 'logging.StreamHandler',
            'formatter': 'api',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'tomato_grading_api': {
            'handlers': ['console', 'api_requests'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'corsheaders': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# ── Email Configuration ─────────────────────────────────────────────────────────
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='gudomacdonald16@gmail.com')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='saec vtnu rkak alqs')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='gudomacdonald16@gmail.com')
FRONTEND_BASE_URL = config('FRONTEND_BASE_URL', default='http://localhost:8081')

# ── Two-Factor Authentication ───────────────────────────────────────────────────
TWO_FACTOR_ENABLED = config('TWO_FACTOR_ENABLED', default=True, cast=bool)
TWO_FACTOR_TOKEN_EXPIRE_MINUTES = config('TWO_FACTOR_TOKEN_EXPIRE_MINUTES', default=10, cast=int)
TWO_FACTOR_MAX_ATTEMPTS = config('TWO_FACTOR_MAX_ATTEMPTS', default=3, cast=int)

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE     = "Africa/Harare"
USE_I18N      = True
USE_TZ        = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
