# Generated by Django 4.2.11 on 2026-03-09 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('total_images', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(max_length=500, upload_to='grading/%Y/%m/%d/')),
                ('predicted_grade', models.CharField(choices=[('A', 'Grade A — Premium'), ('B', 'Grade B — Good'), ('C', 'Grade C — Fair'), ('Reject', 'Reject')], max_length=10)),
                ('grade_code', models.CharField(max_length=6)),
                ('confidence', models.FloatField()),
                ('confidence_level', models.CharField(choices=[('high', 'High (≥85%)'), ('medium', 'Medium (60–85%)'), ('low', 'Low (<60%)')], max_length=10)),
                ('all_probabilities', models.JSONField(default=dict)),
                ('inference_time_ms', models.FloatField(default=0.0)),
                ('model_version', models.CharField(default='1.0.0', max_length=20)),
                ('manual_review', models.BooleanField(default=False)),
                ('marketable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grading_sessions', to='tomato_grading_api.batchsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grading_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('model_type', models.CharField(choices=[('grading', 'Grading Model (Random Forest)'), ('pricing', 'Pricing Model (XGBoost/LightGBM)')], max_length=20)),
                ('accuracy', models.FloatField(blank=True, help_text='Test accuracy (grading) or R² (pricing)', null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, help_text='RMSE USD/kg (pricing only)', null=True)),
                ('mape', models.FloatField(blank=True, help_text='MAPE % (pricing only)', null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('model_file', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-deployed_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('market_location', models.CharField(max_length=150)),
                ('month', models.CharField(max_length=20)),
                ('market_type', models.CharField(max_length=30)),
                ('farm_lat', models.FloatField(blank=True, null=True)),
                ('farm_lon', models.FloatField(blank=True, null=True)),
                ('imputed_features', models.JSONField(default=dict, help_text='All 18 pricing model features after imputation.')),
                ('resolution_log', models.JSONField(default=dict, help_text='Per-feature source tags (user_input | rule_based | geo_lookup | historical_mode | statistical_default | haversine_calculation).')),
                ('imputation_warnings', models.JSONField(default=list, help_text='Any warnings raised during feature imputation.')),
                ('predicted_price', models.FloatField(help_text='Point estimate in USD/kg.')),
                ('price_range_low', models.FloatField(help_text='Lower bound of confidence interval in USD/kg.')),
                ('price_range_high', models.FloatField(help_text='Upper bound of confidence interval in USD/kg.')),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('pricing_model_version', models.CharField(default='1.0.0', max_length=20)),
                ('inference_time_ms', models.FloatField(default=0.0)),
                ('total_pipeline_time_ms', models.FloatField(default=0.0, help_text='Total elapsed time for the full Grade+Impute+Price pipeline.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('grading_session', models.OneToOneField(help_text='The grading event that supplied the grade for this pricing prediction.', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_session', to='tomato_grading_api.gradingsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_price', models.FloatField(help_text='Actual price the tomatoes sold for (USD/kg)')),
                ('price_was_wrong', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='tomato_grading_api.pricingsession')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GradingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_grade', models.CharField(choices=[('A', 'Grade A — Premium'), ('B', 'Grade B — Good'), ('C', 'Grade C — Fair'), ('Reject', 'Reject')], max_length=10)),
                ('model_was_wrong', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='tomato_grading_api.gradingsession')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='pricingsession',
            index=models.Index(fields=['user', '-created_at'], name='tomato_grad_user_id_8585e7_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingsession',
            index=models.Index(fields=['market_location'], name='tomato_grad_market__19abff_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingsession',
            index=models.Index(fields=['market_type'], name='tomato_grad_market__e53b77_idx'),
        ),
        migrations.AddIndex(
            model_name='gradingsession',
            index=models.Index(fields=['user', '-created_at'], name='tomato_grad_user_id_645e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='gradingsession',
            index=models.Index(fields=['predicted_grade'], name='tomato_grad_predict_8c03f7_idx'),
        ),
    ]
