# Generated by Django 4.2.11 on 2026-03-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomato_grading_api', '0003_userprofile_products'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='tomato_grad_is_acti_ea280b_idx',
            old_name='tomato_grad_is_acti_7e2d6a_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='tomato_grad_county_73c1e4_idx',
            old_name='tomato_grad_county_4d98c1_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='tomato_grad_categor_427bbb_idx',
            old_name='tomato_grad_category_3c1c89_idx',
        ),
    ]
