# Generated by Django 4.2.11 on 2026-03-23 08:48

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tomato_grading_api', '0005_add_userprofile_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('crops', models.JSONField(default=list, help_text='List of crops farmer grows')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('farm_size', models.CharField(blank=True, help_text='Farm size in hectares', max_length=50)),
                ('years_experience', models.IntegerField(default=0)),
                ('business_phone', models.CharField(blank=True, max_length=30)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('social_media', models.JSONField(default=dict, help_text='Social media links')),
                ('certifications', models.JSONField(default=list, help_text='List of certifications')),
                ('active_listings', models.IntegerField(default=0)),
                ('total_sales', models.IntegerField(default=0)),
                ('response_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Response rate percentage', max_digits=5)),
                ('avg_response_time', models.IntegerField(default=0, help_text='Average response time in hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tomato_grading_api.county')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating', '-created_at'],
            },
        ),
    ]
