# Generated by Django 4.2.11 on 2026-03-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomato_grading_api', '0006_county_productcategory_farmerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
