# Generated by Django 4.2.11 on 2026-03-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tomato_grading_api", "0008_passwordreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="verification_code",
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
